"""remove rol column

Revision ID: 0b5fea128ef2
Revises: 899e5e5c5cdb
Create Date: 2026-03-20 05:26:36.115391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b5fea128ef2'
down_revision = '899e5e5c5cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('rol')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', mysql.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
