"""remove rol, add anulada iva subtotal

Revision ID: 1290c49de14f
Revises: 158e15b3392f
Create Date: 2026-03-20 06:19:33.945902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1290c49de14f'
down_revision = '158e15b3392f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('iva_porcentaje', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_column('iva_porcentaje')
        batch_op.drop_column('subtotal')

    # ### end Alembic commands ###
