"""anulada y fecha_anulacion en ventas, remove rol

Revision ID: 158e15b3392f
Revises: 0b5fea128ef2
Create Date: 2026-03-20 05:44:54.484574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158e15b3392f'
down_revision = '0b5fea128ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anulada', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fecha_anulacion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_column('fecha_anulacion')
        batch_op.drop_column('anulada')

    # ### end Alembic commands ###
