"""agregar stock actual a productos

Revision ID: 899e5e5c5cdb
Revises: 486ebffe4331
Create Date: 2026-03-16 07:21:59.359554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '899e5e5c5cdb'
down_revision = '486ebffe4331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_actual', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=mysql.ENUM('admin', 'operario', 'consultor'),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('admin', 'operario', 'consultor'),
               existing_nullable=True)

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('stock_actual')

    # ### end Alembic commands ###
