"""agregar_campanas

Revision ID: c8d75935ca55
Revises: a3f7c2d91e05
Create Date: 2026-03-22 22:06:31.442776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d75935ca55'
down_revision = 'a3f7c2d91e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campanas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('activa', 'cerrada'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campana_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'campanas', ['campana_id'], ['id'])

    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campana_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'campanas', ['campana_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('campana_id')

    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('campana_id')

    op.drop_table('campanas')
    # ### end Alembic commands ###
