"""migracion final

Revision ID: f7734de8ac2e
Revises: a1b2c3d4e5f6
Create Date: 2026-03-26 06:41:21.159868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7734de8ac2e'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.alter_column('activo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.alter_column('activo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
